name: NextJS pipline

on: 
  push:
    branches:
      - master

jobs:
    job1:
      name: my Name is Job1
      runs-on: ubuntu-latest
      steps:
        - name : First Step - JOb 1
          run: echo "First Step in Job 1"

        - name: Create a File
          run: touc test.txt
    job2:
        name: my Cast is Job2
        runs-on: ubauntu-latest
        steps:
          - name: Verfiy the File - Job 2
            run : ls - 1